name: LAPRAS Card

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: 'msk1206'
          ICON_FIRST: "#212121"
          ICON_SECOND: "#818181"
          BACKGROUND_FIRST: "#232323"
          BACKGROUND_SECOND: "#6d6d6d"
          LANG: 'ja'
          CARD_WIDTH: '350'
          UPDATE_TIME: 'false'
